version: "2.0"
services:
  app:
    build: .
    links:
      - selenium-hub
      - selenium-chrome
    depends_on:
      - selenium-chrome
      - selenium-hub
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  selenium-chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444